const Alphabets = [
  { letter: "a", image: "./alphabet/a.png" },
  { letter: "b", image: "./alphabet/b.png" },
  { letter: "c", image: "./alphabet/c.png" },
  { letter: "d", image: "./alphabet/d.png" },
  { letter: "e", image: "./alphabet/e.png" },
  { letter: "f", image: "./alphabet/f.png" },
  { letter: "g", image: "./alphabet/g.png" },
  { letter: "h", image: "./alphabet/h.png" },
  { letter: "i", image: "./alphabet/i.png" },
  { letter: "j", image: "./alphabet/j.png" },
  { letter: "k", image: "./alphabet/k.png" },
  { letter: "l", image: "./alphabet/l.png" },
  { letter: "m", image: "./alphabet/m.png" },
  { letter: "n", image: "./alphabet/n.png" },
  { letter: "o", image: "./alphabet/o.png" },
  { letter: "p", image: "./alphabet/p.png" },
  { letter: "q", image: "./alphabet/q.png" },
  { letter: "r", image: "./alphabet/r.png" },
  { letter: "s", image: "./alphabet/s.png" },
  { letter: "t", image: "./alphabet/t.png" },
  { letter: "u", image: "./alphabet/u.png" },
  { letter: "v", image: "./alphabet/v.png" },
  { letter: "w", image: "./alphabet/w.png" },
  { letter: "x", image: "./alphabet/x.png" },
  { letter: "y", image: "./alphabet/y.png" },
  { letter: "z", image: "./alphabet/z.png" },
];
const Profile = [
  { image: "./boy/b1.png" },
  { image: "./boy/b2.png" },
  { image: "./boy/b3.png" },
  { image: "./boy/b4.png" },
  { image: "./boy/b5.png" },
  { image: "./boy/b6.png" },
  { image: "./boy/b7.png" },
  { image: "./girl/g1.png" },
  { image: "./girl/g2.png" },
  { image: "./girl/g3.png" },
  { image: "./girl/g4.png" },
  { image: "./girl/g5.png" },
  { image: "./girl/g6.png" },
];

export { Alphabets, Profile };
